# -*- coding: utf-8 -*-
"""Lora-Flaubert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iyQWWXtyukj50T1Vr0bWvlg0Qxt3IIQh
"""

!pip install sacremoses

import torch
import numpy as np
from datasets import load_dataset
from transformers import (
    FlaubertTokenizer,
    FlaubertForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding,
)
from peft import LoraConfig, get_peft_model, TaskType
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

# -------------------------------------------------
# Configuration
# -------------------------------------------------
MODEL_NAME = "flaubert/flaubert_base_cased"
OUTPUT_DIR = "./flaubert-lora"

BATCH_SIZE = 8
EPOCHS = 3
LR = 2e-4
MAX_LENGTH = 128
TEST_SIZE = 0.2
SEED = 42

TRAIN_JSONL = "train_allocine.jsonl"
EVAL_JSONL = "eval_allocine.jsonl"

# -------------------------------------------------
# Device detection
# -------------------------------------------------
if torch.cuda.is_available():
    DEVICE = torch.device("cuda")
elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
    DEVICE = torch.device("mps")
else:
    DEVICE = torch.device("cpu")

print(f"Using device: {DEVICE}")

# -------------------------------------------------
# Load Allociné dataset and save to jsonl
# -------------------------------------------------
raw_dataset = load_dataset("allocine")
split_dataset = raw_dataset["train"].train_test_split(test_size=TEST_SIZE, seed=SEED)

split_dataset["train"].to_json(TRAIN_JSONL)
split_dataset["test"].to_json(EVAL_JSONL)

print(f"Saved training split to {TRAIN_JSONL}")
print(f"Saved evaluation split to {EVAL_JSONL}")

# Reload from jsonl to simulate your real project pipeline
train_dataset = load_dataset("json", data_files=TRAIN_JSONL, split="train")
eval_dataset = load_dataset("json", data_files=EVAL_JSONL, split="train")

# -------------------------------------------------
# Tokenizer
# -------------------------------------------------
tokenizer = FlaubertTokenizer.from_pretrained(MODEL_NAME)

if tokenizer.pad_token is None:
    tokenizer.add_special_tokens({"pad_token": "<pad>"})

# -------------------------------------------------
# Preprocessing
# Allociné fields: review, label
# -------------------------------------------------
def preprocess(example):
    return {
        "text": example["review"],
        "label": int(example["label"])
    }

train_dataset = train_dataset.map(preprocess)
eval_dataset = eval_dataset.map(preprocess)

# -------------------------------------------------
# Tokenization
# -------------------------------------------------
def tokenize(example):
    return tokenizer(
        example["text"],
        truncation=True,
        max_length=MAX_LENGTH,
    )

train_dataset = train_dataset.map(tokenize)
eval_dataset = eval_dataset.map(tokenize)

# Rename label -> labels for Trainer
if "label" in train_dataset.column_names:
    train_dataset = train_dataset.rename_column("label", "labels")
if "label" in eval_dataset.column_names:
    eval_dataset = eval_dataset.rename_column("label", "labels")

# Remove unused columns
keep_cols = {"input_ids", "attention_mask", "labels"}
train_remove_cols = [col for col in train_dataset.column_names if col not in keep_cols]
eval_remove_cols = [col for col in eval_dataset.column_names if col not in keep_cols]

if train_remove_cols:
    train_dataset = train_dataset.remove_columns(train_remove_cols)
if eval_remove_cols:
    eval_dataset = eval_dataset.remove_columns(eval_remove_cols)

print(f"Train size: {len(train_dataset)}")
print(f"Eval size: {len(eval_dataset)}")

# -------------------------------------------------
# Model
# -------------------------------------------------
model = FlaubertForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2,
)

model.config.pad_token_id = tokenizer.pad_token_id
model.resize_token_embeddings(len(tokenizer))

# -------------------------------------------------
# LoRA configuration
# FlauBERT / XLM-style attention modules
# -------------------------------------------------
lora_config = LoraConfig(
    task_type=TaskType.SEQ_CLS,
    inference_mode=False,
    r=8,
    lora_alpha=32,
    lora_dropout=0.1,
    target_modules=["q_lin", "v_lin"],
    bias="none",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

model = model.to(DEVICE)

# -------------------------------------------------
# Metrics
# -------------------------------------------------
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        preds,
        average="binary",
        zero_division=0,
    )
    acc = accuracy_score(labels, preds)

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1,
    }

# -------------------------------------------------
# Data collator
# -------------------------------------------------
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

# -------------------------------------------------
# Training arguments
# Note: your environment uses eval_strategy
# -------------------------------------------------
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    num_train_epochs=EPOCHS,
    learning_rate=LR,
    logging_steps=10,
    eval_strategy="epoch",
    save_strategy="epoch",
    report_to="none",
    load_best_model_at_end=False,
    remove_unused_columns=True,
)

# -------------------------------------------------
# Trainer
# -------------------------------------------------
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

# -------------------------------------------------
# Train
# -------------------------------------------------
print("Starting FlauBERT LoRA training on Allociné...")
trainer.train()

# -------------------------------------------------
# Evaluate
# -------------------------------------------------
print("Evaluating...")
results = trainer.evaluate()
print("Evaluation results:", results)

# -------------------------------------------------
# Save
# -------------------------------------------------
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print(f"Training complete. Model saved to: {OUTPUT_DIR}")